config/routes.rb
Rails.application.routes.draw do
  
  # root 'students#index'

  root "home#index"

  resources :students

  resources :users, only: [:new, :create, :index, :show]

  resources :courses

  resources :projects, only: [:new, :create]


  # resources :sessions
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'

  delete '/sign_out', to: 'sessions#destroy'

end

app/models/cour.rb
class Cour < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :student

  validates :name, presence: true

  #how about making sure that the project has a student associated w it

end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  has_many :projects

  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate
    unless current_user
      redirect_to root_path, alert: "Must be logged in to view this website!"
    end
  end

  private

  def current_user
    # inspect session hash and look for a user_id
    # if an id exists, then search the database for that id
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :authenticate

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find_by_id(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      flash[:notice] = "Course has saved successfully"
      redirect_to course_path(@course)
    else
      render :new
    end
  end

  def edit
    @course = Course.find_by_id(params[:id])
  end

  def update
    @course = Course.find_by_id(params[:id])

    if @course.update_attributes(course_params) 
      flash[:notice] = "Course was successfully updated."
      redirect_to course_path(@course)
    else
      flash[:alert] = "Course was not updated."
      render :edit
    end

  end

  def destroy
    @course = Course.find_by_id(params[:id])
    @course.destroy
    flash[:notice] = "Course was successfully deleted."
    redirect_to courses_path
  end

private

  def course_params
    params.require(:course).permit(:name)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project was saved."
      redirect_to students_path
    else
      
    end
  end


  private

  def project_params
    params.require(:project).permit(:name,:student_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :authenticate, only: [:destroy]

  def new
  end

  def create

    #find user by email address

    @user = User.find_by_email(params[:email])


    #if user exists and user is authenticated log them in

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Signed In"
      redirect_to students_path
    else
      render :new
      flash.now[:alert] = "Invalid email or password"
    end

    #if not, render :new view
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Successfully logged out"
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	before_action :authenticate

	def index
		# make active record request for all students
		# store the result in a variable called @students
		@students = Student.all
	end

	def show
		@student = Student.find_by_id(params[:id])
	end

	def new
		@student = Student.new
	end

	def create
		binding.pry
		# Initialize a new student object with form values
		@student = Student.new(student_params)

		# Condition: if student was successfully create redirect to index view
		# and display flash message

		if @student.save
			flash[:notice] = "Student was successfully created!"
			redirect_to student_path(@student)
		else
			render :new
			# redirect_to new_student_path
		end

	end

	def edit
		@student = Student.find_by_id(params[:id])
	end

	def update
		binding.pry
		@student = Student.find_by_id(params[:id])		

		if @student.update_attributes(student_params)
			flash[:notice] = "Student was successfully updated."
			redirect_to student_path(@student)
		else 
			render :edit
		end
	end

	def destroy
		@student = Student.find_by_id(params[:id])		
		@student.destroy
		flash[:notice] = "Student was successfully removed."
		redirect_to students_path

	end


	private

	def student_params
		
		params.require(:student).permit(:first_name,:last_name,:phone,:email,:status, :course_ids=>[])
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)

    if @user.save
      #add flash message and redirect to students index page
      flash[:notice] = "New user successfully created"
      redirect_to students_path
    else
      #render the new view
      flash[:alert] = "Problem creating new user... Please try agin."
      render :new
    end

  end


private

  def user_params
    params.require(:user).permit(:full_name,:email,:password,:password_confirmation)
  end 



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <% if @course.errors.any? %>
    <div id = "error_explanation">

      <h2>The following <%= pluralize(@course.errors.count, "error")%> prevented this course from being saved.</h2>
      <ul>
        <% @course.errors.full_messages.each do |error| %>
          <li>
              <%= error %>
          </li>
        <%end%>
      </ul> 
    </div>
  <%end%>


  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
    
  <%= f.submit %>

<% end %>

app/views/courses/edit.html.erb
<h1> Edit Courses </h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1> Course Roster </h1>

<ul>
  <% @courses.each do |course| %>
    <li>
      <span> <%= link_to(course.name, course_path(course))%> </span> 
      <span> <%= link_to("Delete",course_path(course), method: :delete, data: {confirm: "Are you sure you want to delete this course?"}) %>
    </li>
  <% end %>
</ul>

<%= button_to("Add New Course", new_course_path, method: :get) %>

app/views/courses/new.html.erb
<h1> New Courses </h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1> ~~ Course Details ~~ </h1>

<p><%= link_to("Edit", edit_course_path(@course)) %></p>

<% if @course %>
  <p><span>Course Name: <%=@course.name%></span></p>
<% else %>
  <p> Course not found </p>
<% end %>

<p><%= link_to("Back",courses_path) %></p>

app/views/home/index.html.erb
<h1>  Homepage !!! </h1>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <ul>
    <% if current_user %>
      <li> Welcome, <%= current_user.email %> </li>
      <li> <%= link_to('Sign Out', sign_out_path, method: :delete) %> </li>
    <% else %>
      <li> <%= link_to('Register', new_user_path) %> </li>
    
      <li> <%= link_to('Sign In', sign_in_path) %> </li>
    
    <% end %>  

    <li><%= link_to('Students', students_path) %></li>
    <li><%= link_to('Courses', courses_path) %></li>
    <li><%= link_to('Users', users_path) %></li>
    
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NycdaSma</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
   
    <!-- <nav> Nav-Bar coming soon  </nav> -->
    
    <%= render  '/layouts/navigation' %>

    <%= flash[:notice] if flash[:notice] %>
    <%= flash[:alert] if flash[:alert] %>

  <%= yield %>

  </body>
</html>

app/views/projects/new.html.erb
<h1>  Add New Project </h1>

<%= form_for @project do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :student_id %>
    <%= collection_select(:project, :student_id, Student.all, :id, :email, prompt:true) %>
  </div>

  <div>
     <%= f.submit %> 
  </div>
 
<% end %>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <% if @student.errors.any? %>
    <div id = "error_explanation">

      <h2>The following <%= pluralize(@student.errors.count, "error")%> prevented this student from being saved.</h2>
      <ul>
        <% @student.errors.full_messages.each do |error| %>
          <li>
              <%= error %>
          </li>
        <%end%>
      </ul> 
    </div>
  <%end%>


  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  
  <div>
    <%= collection_check_boxes(:student, :course_ids, Course.all, :id, :name) %>
  </div>


  <%= f.submit %>

<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h1> STUDENTS!!! </h1>



<ul>
	<% @students.each do |student| %>
		<li>
			<span> <%= link_to(student.first_name, student_path(student)) %> </span> | 
			<span> <%= student.last_name %> </span> | 
			<span> <%= student.email %> </span> | 
			<span> <%= student.phone %> </span>	
      <span> <%= link_to("Delete",student_path(student), method: :delete, data: {confirm: "Are you sure you want to delete this student?"}) %>
		</li>
	<% end %>
</ul>

<%= button_to("Add New Student", new_student_path, method: :get) %>

app/views/students/new.html.erb
<h1>Add New Student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<h1> ~~ Student Details ~~ </h1>

<p><%= link_to("Edit", edit_student_path(@student)) %></p>

<% if @student %>
	<p><span>First Name: <%=@student.first_name%></span></p>
	<p><span>Last Name:  <%=@student.last_name%></span></p>
	<p><span>Email:      <%=@student.email%></span></p>
	<p><span>Phone:      <%=@student.phone%></span></p>
	<p><span>Status:     <%=@student.status%></span></p>

  <h2>Projects:</h2>
  <ul>
    <% @student.projects.each do |project| %>
      <li> <%= project.name %> </li>
    <% end %>
  </ul>

<h2>Courses:</h2>
  <ul>
    <% @student.courses.each do |course| %>
      <li> <%= course.name %> </li>
    <% end %>
  </ul>



<% else %>
	<p>	Student not found </p>
<% end %>

<p><%= link_to("Back",students_path) %></p>

app/views/users/index.html.erb
<h1> Users List </h1>


<ul>
  <%= @users.each do |user| %>
    <li> <%=link_to(user.full_name,user_path(user))%></li>
  <%end%>

</ul> 

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>


<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id = "error_explanation">

      <h2>The following <%= pluralize(@user.errors.count, "error")%> prevented this user from being saved.</h2>
      <ul>
        <% @user.errors.full_messages.each do |error| %>
          <li>
              <%= error %>
          </li>
        <%end%>
      </ul> 
    </div>
  <%end%>


  <div>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>
  
  <%= f.submit "Sign-up"%>

<% end %>